### ISSUE TITLE
Error after i enter my username

### ISSUE THREAD

**Issue by andrewc2048** [RishiTiku/InstagramJSONToReadableText#3]
![Error](https://user-images.githubusercontent.com/23151579/65161471-8c14c400-da2f-11e9-86c2-87ddced6ebcb.PNG)

**Comment by RishiTiku** [comment]
@andrewc2048 Hi there, Andrew!
So python says Extra Data. See, this error is popping up because the data you've put in messages.json is not pure json. There might be some brackets missing, there might be some extra brackets that may have entered. Please edit your messages.json file using a text editor. This is the first time I'm encountering this issue. Seems like your messages.json has been rewritten. Please check for it. There is no error in the program. Also if you don't have any issues, send me a copy of your messages.json with your username at sunilrobin786@gmail.com for a custom solution. I promise you all privacy.

**Comment by andrewc2048** [comment]
All sorted. I had edited it to not contain somone.
Thank you
